name: Deploying template

on: push

run-name: Deploy to ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - run: echo "This job deploys to ${{ inputs.environment }}"
      - run: pm2 delete greetings-app-${{ inputs.environment }} || true
        working-directory: greetings
      - run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
        working-directory: greetings
