name: GitHub Actions

on: push

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - run: echo "This job installs pip dependencies"
      - run: pip install -r requirements.txt
        working-directory: greetings

  deploy-to-dev:
    uses: ./.github/actions/deploy.yml
    # steps:
    #   - name: Deploy
    #     uses: "./.github/actions"
    #     with:
    #       environment: dev
    #       port: 7001

  # deploy-to-prod:
  #   runs-on: self-hosted
  #   needs: tests-on-preprod
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.5.2
  #       with:
  #         repository: mtararujs/python-greetings
  #         path: greetings
  #     - run: echo "This job deploys to prod"
  #     - run: pm2 delete greetings-app-dev || true
  #     - run: pm2 start app.py --name greetings-app-dev -- --port 7004

  # Tests-on-prod:
  #   runs-on: self-hosted
  #   needs: deploy-to-prod
  #   steps:
  #     - run: echo "This job runs tests on prod"
